/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.i2pm;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
